-- Insertar productos
INSERT INTO crud_product (name, sku, status, category, created_at, updated_at) VALUES
('Camiseta Básica', 'SKU001', 'published', 'standard', NOW(), NOW()),
('Jeans Ajustados', 'SKU002', 'draft', 'premium', NOW(), NOW()),
('Zapatos de Cuero', 'SKU003', 'published', 'vip', NOW(), NOW()),
('Chaqueta Impermeable', 'SKU004', 'archived', 'standard', NOW(), NOW()),
('Gorra Deportiva', 'SKU005', 'published', 'standard', NOW(), NOW()),
('Bufanda de Lana', 'SKU006', 'draft', 'premium', NOW(), NOW()),
('Reloj Digital', 'SKU007', 'published', 'vip', NOW(), NOW()),
('Gafas de Sol', 'SKU008', 'archived', 'vip', NOW(), NOW()),
('Bolso de Mano', 'SKU009', 'draft', 'premium', NOW(), NOW()),
('Botas de Montaña', 'SKU010', 'published', 'premium', NOW(), NOW()),
('Camisa Formal', 'SKU011', 'published', 'standard', NOW(), NOW()),
('Pantalones Cortos', 'SKU012', 'draft', 'standard', NOW(), NOW()),
('Tenis Deportivos', 'SKU013', 'published', 'vip', NOW(), NOW()),
('Abrigo de Invierno', 'SKU014', 'archived', 'premium', NOW(), NOW()),
('Sombrero de Paja', 'SKU015', 'draft', 'standard', NOW(), NOW()),
('Pijama de Algodón', 'SKU016', 'published', 'standard', NOW(), NOW()),
('Sandalias de Playa', 'SKU017', 'draft', 'vip', NOW(), NOW()),
('Chaqueta de Cuero', 'SKU018', 'published', 'vip', NOW(), NOW()),
('Cinturón de Cuero', 'SKU019', 'archived', 'premium', NOW(), NOW()),
('Camiseta Estampada', 'SKU020', 'published', 'standard', NOW(), NOW()),
('Short Deportivo', 'SKU021', 'draft', 'standard', NOW(), NOW()),
('Zapatillas de Casa', 'SKU022', 'archived', 'standard', NOW(), NOW()),
('Lentes de Lectura', 'SKU023', 'published', 'vip', NOW(), NOW()),
('Guantes Térmicos', 'SKU024', 'draft', 'premium', NOW(), NOW()),
('Chaqueta de Jean', 'SKU025', 'published', 'standard', NOW(), NOW()),
('Falda Plisada', 'SKU026', 'archived', 'premium', NOW(), NOW()),
('Camiseta sin Mangas', 'SKU027', 'draft', 'standard', NOW(), NOW()),
('Mochila Escolar', 'SKU028', 'published', 'premium', NOW(), NOW()),
('Zapatos Formales', 'SKU029', 'archived', 'vip', NOW(), NOW()),
('Pantalón de Vestir', 'SKU030', 'published', 'premium', NOW(), NOW());

-- Insertar etiquetas
INSERT INTO crud_tag (title, description) VALUES
('Verano', 'Productos ideales para el clima cálido'),
('Invierno', 'Accesorios y ropa para clima frío'),
('Deportivo', 'Ropa diseñada para actividades físicas'),
('Casual', 'Uso diario y estilo informal'),
('Elegante', 'Diseños formales o de gala'),
('Urbano', 'Estilo juvenil y de ciudad'),
('Alta Gama', 'Productos de lujo o VIP'),
('Resistente', 'Diseñado para durar'),
('Tendencia', 'Últimas modas y estilos'),
('Accesorio', 'Complementos como relojes o bolsos'),
('Oficina', 'Prendas adecuadas para el entorno laboral'),
('Fiesta', 'Ideal para celebraciones y eventos'),
('Minimalista', 'Diseño simple y moderno'),
('Clásico', 'Estilo atemporal que nunca pasa de moda'),
('Ecológico', 'Hecho con materiales sostenibles'),
('Tecnológico', 'Integración de tecnología en el producto'),
('Unisex', 'Apto para cualquier género'),
('Juvenil', 'Diseñado para el público joven'),
('Profesional', 'Enfocado en uso laboral o ejecutivo'),
('Cómodo', 'Enfocado en la comodidad del usuario'),
('Ligero', 'Materiales livianos para mayor confort'),
('Impermeable', 'Resistente al agua'),
('Reversible', 'Uso doble con diseño distinto'),
('Temporada', 'Ediciones limitadas por estación'),
('Transpirable', 'Permite la ventilación del cuerpo'),
('Ajustable', 'Se adapta a diferentes tamaños o formas'),
('Multifuncional', 'Con varios usos o formas de llevarse'),
('Edición Especial', 'Producto único o conmemorativo'),
('Hecho a Mano', 'Fabricación artesanal'),
('Clima Extremo', 'Preparado para condiciones severas');

-- Insertar relaciones ProductTag (producto-etiqueta)
INSERT INTO crud_producttag (product_id, tag_id, relevance) VALUES
(1, 3, 4), (1, 5, 6),
(1, 1, 7), (1, 4, 8),
(2, 4, 6), (2, 9, 9), (2, 2, 3),
(3, 5, 10), (3, 7, 9), (3, 10, 6),
(4, 2, 8), (4, 8, 7),
(5, 1, 6), (5, 3, 5),
(6, 2, 9), (6, 5, 4), (6, 10, 3),
(7, 7, 10), (7, 10, 9),
(8, 6, 8), (8, 9, 5), (8, 4, 4),
(9, 10, 7), (9, 5, 5),
(10, 8, 9), (10, 2, 6), (10, 6, 5),

-- Etiquetas asociadas a múltiples productos
(1, 9, 4), -- Tendencia en otro producto
(2, 1, 3), -- Verano en Jeans
(4, 6, 7); -- Urbano en Chaqueta